### ISSUE TITLE
Java version issue when trying the example

### ISSUE THREAD

**Issue by MadeInPierre** [ACassimiro/TSNsched#24]
Hi! 

Apologies for the beginner question. I am trying to run the example use case under the `Script` directory. The `./install-dependencies.sh` script finished without issues until the example. At first, I unfortunately had this error when running the example script with Java 8 or 11:

```sh
$ ./generateSchedule.sh example.java
rm: cannot remove 'output/*': No such file or directory
:./libs/com.microsoft.z3.jar:./libs/gson-2.8.6.jar:./libs/java-json.jar:./libs/TSNsched.jar
UseCase.java:1: error: cannot access JSONParser
import com.tsnsched.core.interface_manager.JSONParser;
                                          ^
  bad class file: ./libs/TSNsched.jar(/com/tsnsched/core/interface_manager/JSONParser.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
[...]
```

It seemed like the `.jar` lib files were complied using Java 17 (version `61.0` shown above) while version 11 was expected (version `55.0`). The same happens when trying with Java 8, except `55.0` is replaced by `52.0`.

I then tried to install Java 17 and run the script with it, but I get a different error:

```
$ ./generateSchedule.sh example.java                                        
rm: cannot remove 'output/*': No such file or directory
:./libs/com.microsoft.z3.jar:./libs/gson-2.8.6.jar:./libs/java-json.jar:./libs/TSNsched.jar
Exception in thread "main" java.lang.NoSuchMethodError: 'void com.microsoft.z3.Solver.add(com.microsoft.z3.Expr[])'
        at com.tsnsched.core.components.Port.setUpCycle(Port.java:1377)
        at com.tsnsched.core.nodes.TSNSwitch.setUpCycleSize(TSNSwitch.java:418)
        at com.tsnsched.core.schedule_generator.ScheduleGenerator.configureNetwork(ScheduleGenerator.java:159)
        at com.tsnsched.core.schedule_generator.ScheduleGenerator.generateSchedule(ScheduleGenerator.java:257)
        at UseCase.runTestCase(UseCase.java:453)
        at GenerateScheduleJavaInput.main(GenerateScheduleJavaInput.java:15)
mv: cannot move 'output.txt' to 'output/example.java.out': No such file or directory
mv: cannot stat 'log.txt': No such file or directory
mv: cannot stat 'output.json': No such file or directory
Ending execution
```

Is there an obvious mistake? I see that the installation script installs Java 8, but I haven't figured out what could be wrong.
Thank you for your help!

**Comment by MadeInPierre** [comment]
Well, I reverted your last commit on March 7th `7ac00ad` for M1 compatibility and everything works fine now! Maybe there is something new that breaks compatibility for other systems? I am using a regular x86 PC with Ubuntu 22.04.

I will close this issue since it is (kindof) solved, but feel free to open it again in case you want to investigate about the last commit's effects.

**Comment by ACassimiro** [comment]
Hello @MadeInPierre! Sorry for reaching out so late, and thank you for figuring this out. I'm going to take a deeper look into it and should push a patch for fixing it in the next few days.

**Comment by ghjk138243** [comment]
> 你好！
> 
> 為初學者的問題道歉。我正在嘗試在`Script`目錄下運行示例用例。在示例之前，`./install-dependencies.sh`腳本完成沒有問題。起初，不幸的是，我在使用 Java 8 或 11 運行示例腳本時遇到了這個錯誤：
> 
> ```shell
> $ ./generateSchedule.sh example.java
> rm: cannot remove 'output/*': No such file or directory
> :./libs/com.microsoft.z3.jar:./libs/gson-2.8.6.jar:./libs/java-json.jar:./libs/TSNsched.jar
> UseCase.java:1: error: cannot access JSONParser
> import com.tsnsched.core.interface_manager.JSONParser;
>                                           ^
>   bad class file: ./libs/TSNsched.jar(/com/tsnsched/core/interface_manager/JSONParser.class)
>     class file has wrong version 61.0, should be 55.0
>     Please remove or make sure it appears in the correct subdirectory of the classpath.
> [...]
> ```
> 
> 似乎`.jar`lib 文件是使用 Java 17（`61.0`如上所示的版本）編譯的，而預期是版本 11（版本`55.0`）。嘗試使用 Java 8 時也會發生同樣的情況，除了`55.0`替換為`52.0`.
> 
> 然後我嘗試安裝 Java 17 並使用它運行腳本，但我得到一個不同的錯誤：
> 
> ```
> $ ./generateSchedule.sh example.java                                        
> rm: cannot remove 'output/*': No such file or directory
> :./libs/com.microsoft.z3.jar:./libs/gson-2.8.6.jar:./libs/java-json.jar:./libs/TSNsched.jar
> Exception in thread "main" java.lang.NoSuchMethodError: 'void com.microsoft.z3.Solver.add(com.microsoft.z3.Expr[])'
>         at com.tsnsched.core.components.Port.setUpCycle(Port.java:1377)
>         at com.tsnsched.core.nodes.TSNSwitch.setUpCycleSize(TSNSwitch.java:418)
>         at com.tsnsched.core.schedule_generator.ScheduleGenerator.configureNetwork(ScheduleGenerator.java:159)
>         at com.tsnsched.core.schedule_generator.ScheduleGenerator.generateSchedule(ScheduleGenerator.java:257)
>         at UseCase.runTestCase(UseCase.java:453)
>         at GenerateScheduleJavaInput.main(GenerateScheduleJavaInput.java:15)
> mv: cannot move 'output.txt' to 'output/example.java.out': No such file or directory
> mv: cannot stat 'log.txt': No such file or directory
> mv: cannot stat 'output.json': No such file or directory
> Ending execution
> ```
> 
> 有明顯的錯誤嗎？我看到安裝腳本安裝了 Java 8，但我還沒有弄清楚可能出了什麼問題。 感謝您的幫助！



> 好吧，我在 3 月 7 日恢復了你上次提交`7ac00ad`的 M1 兼容性，現在一切正常！也許有一些新的東西破壞了其他系統的兼容性？我正在使用帶有 Ubuntu 22.04 的普通 x86 PC。
> 
> 我將關閉此問題，因為它（種類）已解決，但如果您想調查最後一次提交的影響，請隨時再次打開它。

Which java version you use to reverted the 7ac00ad?

**Comment by Zitong-tju** [comment]
Hello, I met all the same problems, but when I try to revert your last commit on March 7th, it still display this error:
Exception in thread "main" java.lang.NoSuchMethodError: 'void com.microsoft.z3.Solver.add(com.microsoft.z3.Expr[])'
I don't know what to do.
