### ISSUE TITLE
What went wrong?

### ISSUE THREAD

**Issue by Xszb0000** [ACassimiro/TSNsched#31]
Hello, thanks for your code, but I have some problems. I use version Ubuntu18.04, z3-4.8.13, but running examples always report this error。Please advise?

kaiguoguo@kaiguoguo-virtual-machine:~/Desktop/TSNsched/Script$ ./generateSchedule.sh example.java
:./libs/com.microsoft.z3.jar:./libs/gson-2.8.6.jar:./libs/java-json.jar:./libs/TSNsched.jar
Exception in thread "main" java.lang.NoSuchMethodError: 'void com.microsoft.z3.Solver.add(com.microsoft.z3.Expr[])'
	at com.tsnsched.core.components.Port.setUpCycle(Port.java:1377)
	at com.tsnsched.core.nodes.TSNSwitch.setUpCycleSize(TSNSwitch.java:418)
	at com.tsnsched.core.schedule_generator.ScheduleGenerator.configureNetwork(ScheduleGenerator.java:159)
	at com.tsnsched.core.schedule_generator.ScheduleGenerator.generateSchedule(ScheduleGenerator.java:257)
	at UseCase.runTestCase(UseCase.java:453)
	at GenerateScheduleJavaInput.main(GenerateScheduleJavaInput.java:15)
mv: cannot stat 'log.txt': No such file or directory
mv: cannot stat 'output.json': No such file or directory
Ending execution

**Comment by zeus1024** [comment]
I have encountered the same problem. Have you solved it
